### ISSUE TITLE
Audio? Replication?

### ISSUE THREAD

**Issue by ZenaMel** [mostlyfireproof/R5RVideoPlayer#1]
Do you hear the audio from within Apex?
Do others hear the audio and see the video in-game? (without having the source video files)

I'm thinking we could host cinema parties kind of like they do in VRChat.

**Comment by mostlyfireproof** [comment]
There's no audio in this, only video. I believe there is a way to add custom audio, but only one or two people know how. 
Other people will see the video in game! It uses colored Gibby bubbles, and the colors will show up for everyone.

Cinema parties could be cool, but at the moment, this code slows the server down to half speed, so I'm not sure if that would be possible. There's a lot I can do to optimize it, so that could be possible in the future!
